<img src = "https://escp.eu/sites/default/files/logo/ESCP-logo-white-misalign.svg" width = 400 style="background-color: #240085;">
<h1 align=center><font size = 6>ESCP Business School</font></h1>
<h3 align=center><font size = 5>ESCP Hackathon</font><br/>
<font size = 3>Project 3: Brand sentiment analysis | Criteo</font></h3>
<h6 align=center>Chapter 2: Prepocess for Analysis - WordCount</h6>

Last Updated: March 17, 2021\
Author: Group 07 - Arya Bhattacharya, Hanadi Yachoui, Ming Hin Chung, Resha Dirga

<h3>Chapter Objectives</h3>

<p>This chapter aims to prepare the dataset for wordcount before using it in Tableau.</p>

In [12]:
# Import dependencies
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

from wordcloud import WordCloud, STOPWORDS
import folium
from collections import Counter

In [2]:
# Read dataset for wordcount
df = pd.read_csv('tweets_analysed_cons.csv')
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,id,created_at,in_reply_to_user_id,author_id,text,mentions,source,lang,text_clean,Sentiment,Positive_sentiment,Negative_sentiment
0,0,0,0,1503882954375929866,Tue Mar 15 23:56:51 +0000 2022,NaN,612834201,RT @WrocWW: @AnonOpsSE I found few words to #L...,"['WrocWW', 'AnonOpsSE']",Twitter Web App,en,@WrocWW: @AnonOpsSE I found few words to #Lero...,negative,0.009751,0.990249
1,1,1,0,1503882686380879877,Tue Mar 15 23:55:47 +0000 2022,NaN,612834201,"RT @Ro_manoff: @tashecon Also, please pay atte...","['Ro_manoff', 'tashecon']",Twitter Web App,en,"@Ro_manoff: @tashecon Also, please pay attenti...",positive,0.979445,0.020555
2,2,2,0,1503881899328032771,Tue Mar 15 23:52:40 +0000 2022,NaN,4174651769,RT @NoButYeahBut_: #BoycottDecathlon!!!\n#Deca...,['NoButYeahBut_'],Twitter for Android,en,@NoButYeahBut_: #BoycottDecathlon!!!\n#Decathl...,negative,0.011850,0.988150
3,3,3,0,1503880374874607620,Tue Mar 15 23:46:36 +0000 2022,126267113.0,51585491,@Decathlon @DecathlonUK why are you still doin...,"['Decathlon', 'DecathlonUK']",Twitter for iPhone,en,@Decathlon @DecathlonUK why are you still doin...,negative,0.009619,0.990381
4,4,4,0,1503880275318775809,Tue Mar 15 23:46:13 +0000 2022,NaN,4174651769,"RT @TrudeauMaggie: Auchan, Leroy Merlin, Decat...",['TrudeauMaggie'],Twitter for Android,en,"@TrudeauMaggie: Auchan, Leroy Merlin, Decathlo...",negative,0.088386,0.911614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3569,69,3569,0,1499543192596725760,Fri Mar 04 00:32:11 +0000 2022,NaN,360737613,RT @BoosterVista: Kudos to the MVHS Academic D...,['BoosterVista'],Twitter for iPhone,en,@BoosterVista: Kudos to the MVHS Academic Deca...,positive,0.953905,0.046095
3570,70,3570,0,1499541366673747971,Fri Mar 04 00:24:56 +0000 2022,NaN,3316370737,"RT @jwilliams_mhs: As a team, MHS Academic Dec...",['jwilliams_mhs'],Twitter for iPhone,en,"@jwilliams_mhs: As a team, MHS Academic Decath...",positive,0.986559,0.013441
3571,71,3571,0,1499541283886485507,Fri Mar 04 00:24:36 +0000 2022,NaN,768215814520524801,"As a team, MHS Academic Decathlon came away fr...",[],Twitter for iPhone,en,"As a team, MHS Academic Decathlon came away fr...",positive,0.839740,0.160260
3572,72,3572,0,1499538730570465284,Fri Mar 04 00:14:28 +0000 2022,NaN,1488628891916849156,33239. \nTriathlon n. Athletic contest of thr...,[],botjeelaa,en,33239. \nTriathlon n. Athletic contest of thr...,positive,0.856551,0.143449
3573,73,3573,0,1499535761992994828,Fri Mar 04 00:02:40 +0000 2022,NaN,2784925482,1. Fox\n2. Gretzky\n3. Sinclair\n4. Hughes\n5....,[],Twitter for Android,en,1. Fox\n2. Gretzky\n3. Sinclair\n4. Hughes\n5....,positive,0.608663,0.391337

In [3]:
# Generate function to count words
def word_count(woc):
    return Counter(woc.split())

In [4]:
# Create function to generate clean date
def clean_date(date):
    return date.rsplit(' ',3)[0]

In [9]:
# Data stagging for visualisation
df_woc = df[['Sentiment', 'created_at', 'text_clean']]
df_woc['created_at_group'] = df_woc.apply(lambda x: clean_date(x.created_at), axis=1)
df_woc['text'] = df_woc[['Sentiment','text_clean','created_at_group']].groupby(['Sentiment', 'created_at_group'])['text_clean'].transform(lambda x: ' '.join(x))
df_woc = df_woc[['Sentiment', 'created_at_group', 'text']].drop_duplicates()
df_woc
# df_woc = df_woc.str.cat(sep=' ')
# df_woc = df_woc.split()

# # make define stopwords
# stopwords_ = ['https', 'Decathlon', '@Decathlon', 'decathlon', 't.co']


# for word in STOPWORDS:
#     try:
#         df_woc.remove(word)
#     except:
#         pass
    
# for word in stopwords_:
#     try:
#         df_woc.remove(word)
#     except:
#         pass

# woc = word_count(df_woc)

/var/folders/h0/vgjkl_895611pw1tzh74wq280000gn/T/ipykernel_5712/1050925320.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_woc['created_at_group'] = df_woc.apply(lambda x: clean_date(x.created_at), axis=1)
/var/folders/h0/vgjkl_895611pw1tzh74wq280000gn/T/ipykernel_5712/1050925320.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_woc['text'] = df_woc[['Sentiment','text_clean','created_at_group']].groupby(['Sentiment', 'created_at_group'])['text_clean'].transform(lambda x: ' '.join(x))

,Sentiment,created_at_group,text
0,negative,Tue Mar 15,@WrocWW: @AnonOpsSE I found few words to #Lero...
1,positive,Tue Mar 15,"@Ro_manoff: @tashecon Also, please pay attenti..."
193,neutral,Tue Mar 15,@DecathletesOfEu: In 2019 Jose San Pastor was ...
647,negative,Mon Mar 14,@no_dystopia: @DecathlonUK @whgDawnH @JDSports...
648,positive,Mon Mar 14,@LUKEC4GE GOD NOT MISS DECATHLON @AUSOlympicTe...
663,neutral,Mon Mar 14,@DecathlonUK @whgDawnH @JDSports @SportsDirect...
1008,negative,Sun Mar 13,@jovenatheart @ch0muki Manual car very easy bu...
1009,positive,Sun Mar 13,@Scottcrates Oh yeah. He could probably win a ...
1014,neutral,Sun Mar 13,@bkkj_jinbkk ❤ Decathlon! @michaelmalice I don...
1501,positive,Sat Mar 12,@cmelgarmath: Day 3: Speech and Interview. Tod...
1504,neutral,Sat Mar 12,Check out this deal! Next Day Delivery (Update...
1506,negative,Sat Mar 12,@nexta_tv @AUCHAN_France @leroymerlinfr And de...
1907,positive,Fri Mar 11,#Auchan \n#Decathlon\n#LeroyMerlin\nare contin...
1908,negative,Fri Mar 11,@HeliosRunner @donikroman @DecathlonUK Decathl...
1956,neutral,Fri Mar 11,@NocnaZ: @RafalPrzemysl @leroymerlinfr Decathl...
2101,positive,Thu Mar 10,@KentStTrackXC: 𝓢𝓲𝓰𝓷𝓮𝓭 \n\nWelcome to the #...
2105,negative,Thu Mar 10,@Outkick Just stop Kaepernick. Just stop. Cait...
2139,neutral,Thu Mar 10,@pont_virgule: @olgatokariuk @TotalEnergies @A...
2312,positive,Wed Mar 09,Pearland High places fourth at state Academic ...
2316,negative,Wed Mar 09,@hugodc79 Isto: https://t.co/WlqKtLPHhn @aysha...
2347,neutral,Wed Mar 09,Grazia Leone likes tour #Nikon #Lacoste #adida...
2581,positive,Tue Mar 08,@wyhs: Whitney Young Magnet High School earned...
2582,negative,Tue Mar 08,Y’all voted for this. Not me. And I didn’t vot...
2719,neutral,Tue Mar 08,Check out this deal: https://t.co/hojlMmv91a
2776,positive,Mon Mar 07,"This past weekend, SMCHS hosted the annual Cat..."
2779,negative,Mon Mar 07,"@28Chaz The decathlon one is underrated af, ta..."
2844,neutral,Mon Mar 07,"@MotoThePup In London, you could have a look a..."
2956,positive,Sun Mar 06,@brevkin: Congrats to our 1st place Rhode Isla...
2961,negative,Sun Mar 06,@kyrib @ElektrikGreen @CUBoulder @Solar_Decath...
3028,neutral,Sun Mar 06,Happy 1 year anniversary on my Decathlon 100% ...
3133,positive,Sat Mar 05,@ElRanchoHS: Good luck to @SFrancismath @cmelg...
3135,negative,Sat Mar 05,@ULHScougars: ✔️Academic Decathlon Virtual Sta...
3212,neutral,Sat Mar 05,Compared to yesterday’s skiers who primarily s...
3339,negative,Fri Mar 04,@BoozyMcHound @RouxgarouLA @senorblanxo Try to...
3340,positive,Fri Mar 04,Congrats Academic Decathlon who won awards at ...
3458,neutral,Fri Mar 04,@BodogCA @DamianWarner need to be on this list...

In [13]:
# Count word on text
df_woc['woc'] = df_woc.apply(lambda x: word_count(x.text), axis=1)
df_woc

,Sentiment,created_at_group,text,woc
0,negative,Tue Mar 15,@WrocWW: @AnonOpsSE I found few words to #Lero...,"{'@WrocWW:': 2, '@AnonOpsSE': 2, 'I': 61, 'fou..."
1,positive,Tue Mar 15,"@Ro_manoff: @tashecon Also, please pay attenti...","{'@Ro_manoff:': 12, '@tashecon': 12, 'Also,': ..."
193,neutral,Tue Mar 15,@DecathletesOfEu: In 2019 Jose San Pastor was ...,"{'@DecathletesOfEu:': 15, 'In': 30, '2019': 15..."
647,negative,Mon Mar 14,@no_dystopia: @DecathlonUK @whgDawnH @JDSports...,"{'@no_dystopia:': 1, '@DecathlonUK': 5, '@whgD..."
648,positive,Mon Mar 14,@LUKEC4GE GOD NOT MISS DECATHLON @AUSOlympicTe...,"{'@LUKEC4GE': 1, 'GOD': 1, 'NOT': 1, 'MISS': 1..."
663,neutral,Mon Mar 14,@DecathlonUK @whgDawnH @JDSports @SportsDirect...,"{'@DecathlonUK': 1, '@whgDawnH': 1, '@JDSports..."
1008,negative,Sun Mar 13,@jovenatheart @ch0muki Manual car very easy bu...,"{'@jovenatheart': 1, '@ch0muki': 1, 'Manual': ..."
1009,positive,Sun Mar 13,@Scottcrates Oh yeah. He could probably win a ...,"{'@Scottcrates': 1, 'Oh': 1, 'yeah.': 1, 'He':..."
1014,neutral,Sun Mar 13,@bkkj_jinbkk ❤ Decathlon! @michaelmalice I don...,"{'@bkkj_jinbkk': 1, '❤': 1, 'Decathlon!': 1, '..."
1501,positive,Sat Mar 12,@cmelgarmath: Day 3: Speech and Interview. Tod...,"{'@cmelgarmath:': 5, 'Day': 6, '3:': 6, 'Speec..."
1504,neutral,Sat Mar 12,Check out this deal! Next Day Delivery (Update...,"{'Check': 1, 'out': 1, 'this': 1, 'deal!': 1, ..."
1506,negative,Sat Mar 12,@nexta_tv @AUCHAN_France @leroymerlinfr And de...,"{'@nexta_tv': 20, '@AUCHAN_France': 89, '@lero..."
1907,positive,Fri Mar 11,#Auchan \n#Decathlon\n#LeroyMerlin\nare contin...,"{'#Auchan': 1, '#Decathlon': 2, '#LeroyMerlin'..."
1908,negative,Fri Mar 11,@HeliosRunner @donikroman @DecathlonUK Decathl...,"{'@HeliosRunner': 1, '@donikroman': 1, '@Decat..."
1956,neutral,Fri Mar 11,@NocnaZ: @RafalPrzemysl @leroymerlinfr Decathl...,"{'@NocnaZ:': 1, '@RafalPrzemysl': 1, '@leroyme..."
2101,positive,Thu Mar 10,@KentStTrackXC: 𝓢𝓲𝓰𝓷𝓮𝓭 \n\nWelcome to the #...,"{'@KentStTrackXC:': 4, '𝓢𝓲𝓰𝓷𝓮𝓭': 5, 'Welcome':..."
2105,negative,Thu Mar 10,@Outkick Just stop Kaepernick. Just stop. Cait...,"{'@Outkick': 1, 'Just': 3, 'stop': 5, 'Kaepern..."
2139,neutral,Thu Mar 10,@pont_virgule: @olgatokariuk @TotalEnergies @A...,"{'@pont_virgule:': 3, '@olgatokariuk': 3, '@To..."
2312,positive,Wed Mar 09,Pearland High places fourth at state Academic ...,"{'Pearland': 3, 'High': 4, 'places': 3, 'fourt..."
2316,negative,Wed Mar 09,@hugodc79 Isto: https://t.co/WlqKtLPHhn @aysha...,"{'@hugodc79': 1, 'Isto:': 1, 'https://t.co/Wlq..."
2347,neutral,Wed Mar 09,Grazia Leone likes tour #Nikon #Lacoste #adida...,"{'Grazia': 1, 'Leone': 1, 'likes': 1, 'tour': ..."
2581,positive,Tue Mar 08,@wyhs: Whitney Young Magnet High School earned...,"{'@wyhs:': 6, 'Whitney': 11, 'Young': 7, 'Magn..."
2582,negative,Tue Mar 08,Y’all voted for this. Not me. And I didn’t vot...,"{'Y’all': 1, 'voted': 1, 'for': 12, 'this.': 1..."
2719,neutral,Tue Mar 08,Check out this deal: https://t.co/hojlMmv91a,"{'Check': 1, 'out': 1, 'this': 1, 'deal:': 1, ..."
2776,positive,Mon Mar 07,"This past weekend, SMCHS hosted the annual Cat...","{'This': 3, 'past': 1, 'weekend,': 1, 'SMCHS':..."
2779,negative,Mon Mar 07,"@28Chaz The decathlon one is underrated af, ta...","{'@28Chaz': 1, 'The': 3, 'decathlon': 23, 'one..."
2844,neutral,Mon Mar 07,"@MotoThePup In London, you could have a look a...","{'@MotoThePup': 1, 'In': 1, 'London,': 1, 'you..."
2956,positive,Sun Mar 06,@brevkin: Congrats to our 1st place Rhode Isla...,"{'@brevkin:': 2, 'Congrats': 4, 'to': 30, 'our..."
2961,negative,Sun Mar 06,@kyrib @ElektrikGreen @CUBoulder @Solar_Decath...,"{'@kyrib': 2, '@ElektrikGreen': 3, '@CUBoulder..."
3028,neutral,Sun Mar 06,Happy 1 year anniversary on my Decathlon 100% ...,"{'Happy': 1, '1': 1, 'year': 2, 'anniversary':..."
3133,positive,Sat Mar 05,@ElRanchoHS: Good luck to @SFrancismath @cmelg...,"{'@ElRanchoHS:': 4, 'Good': 6, 'luck': 8, 'to'..."
3135,negative,Sat Mar 05,@ULHScougars: ✔️Academic Decathlon Virtual Sta...,"{'@ULHScougars:': 1, '✔️Academic': 2, 'Decathl..."
3212,neutral,Sat Mar 05,Compared to yesterday’s skiers who primarily s...,"{'Compared': 1, 'to': 3, 'yesterday’s': 1, 'sk..."
3339,negative,Fri Mar 04,@BoozyMcHound @RouxgarouLA @senorblanxo Try to...,"{'@BoozyMcHound': 1, '@RouxgarouLA': 1, '@seno..."
3340,positive,Fri Mar 04,Congrats Academic Decathlon who won awards at ...,"{'Congrats': 2, 'Academic': 29, 'Decathlon': 4..."
3458,neutral,Fri Mar 04,@BodogCA @DamianWarner need to be on this list...,"{'@BodogCA': 1, '@DamianWarner': 1, 'need': 1,..."

In [16]:
# Create function that generate word count for a day
def woc_to_dataframe(woc, date, sentiment):
    words_ = []
    counts_ = []
    dates_ = []
    sentiments_ = []
    for key in woc.keys():
        words_.append(key)
        counts_.append(woc[key])
        dates_.append(date)
        sentiments_.append(sentiment)
    result = {
        'date': dates_,
        'word': words_,
        'count': counts_,
        'sentiment': sentiments_
    }
    
    return pd.DataFrame(result)

In [17]:
# Transform the WordCount to dataframe
df_result = pd.DataFrame()

for index_ in range(0, len(df_woc)):
    df_new = woc_to_dataframe(df_woc.iloc[index_]['woc'],df_woc.iloc[index_]['created_at_group'], df_woc.iloc[index_]['Sentiment'])
    df_result = pd.concat([df_result, df_new])
    
df_result

          date                     word  count sentiment
0   Tue Mar 15                 @WrocWW:      2  negative
1   Tue Mar 15               @AnonOpsSE      2  negative
2   Tue Mar 15                        I     61  negative
3   Tue Mar 15                    found      5  negative
4   Tue Mar 15                      few      2  negative
..         ...                      ...    ...       ...
18  Fri Mar 04                    First      1   neutral
19  Fri Mar 04                     Gold      1   neutral
20  Fri Mar 04                       in      1   neutral
21  Fri Mar 04                      de…      1   neutral
22  Fri Mar 04  https://t.co/mFK1oMwcWP      1   neutral

[21760 rows x 4 columns]

In [18]:
# Export wordcloud
df_result.to_csv('word_cloud.csv')